use chrono::NaiveDate;
use runner::parse::Direction;
use runner::pdf::{lines_from_fragments, reconstruct_statement, Fragment, Page, PdfError};
use rust_decimal::Decimal;
use std::str::FromStr;

/// Real extraction through pdfium — needs the vendored library in
/// sidecars/ (gitignored, like llama-server), so it skips quietly where
/// that's absent (CI). The reconstruction logic above is what CI pins.
#[cfg(feature = "pdf")]
mod extraction {
    use chrono::NaiveDate;
    use runner::parse::{parse_statement_file, Direction};
    use runner::pdf::{extract_lines, extract_pages, reconstruct_statement};
    use rust_decimal::Decimal;
    use std::path::PathBuf;
    use std::str::FromStr;

    #[test]
    fn synthetic_statement_pdf_extracts_reading_order_lines() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let sidecars = root.join("sidecars");
        if !runner::pdf::library_present(&sidecars) {
            eprintln!("skipping: no libpdfium in sidecars/ — see sidecars/README.md");
            return;
        }

        let fixture = root.join("packs/app.kttl.subscription-audit/fixtures/statement-03.pdf");
        let lines = extract_lines(&fixture, &sidecars).unwrap();

        let expected = [
            "ACME BANK Statement January 2025",
            "Date Description Amount",
            "03/01/2025 PUREGYM LTD -24.99",
            "15/01/2025 NETFLIX.COM -10.99",
            // Page 2 follows page 1.
            "Page 2 of 2",
            "28/01/2025 ACME PAYROLL 2450.00",
        ];
        assert_eq!(lines, expected, "{lines:#?}");
    }

    /// `statement-04.pdf` has what a real statement has and
    /// `statement-03.pdf` does not: separate **Paid Out** / **Paid In** /
    /// **Balance** columns, an empty money column on every row, both
    /// directions, and six pages of repeated headers and furniture. It is
    /// generated by `make-statement-04.py` beside it, so it can be
    /// extended; `statement-04.csv` describes the same transactions and is
    /// the oracle #137 must match.
    ///
    /// What this test pins is the fixture, not reconstruction — that is
    /// #137's job. It exists so that the fixture cannot quietly stop
    /// exercising the thing it was built to exercise.
    #[test]
    fn statement_04_lines_alone_cannot_tell_money_out_from_money_in() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let sidecars = root.join("sidecars");
        if !runner::pdf::library_present(&sidecars) {
            eprintln!("skipping: no libpdfium in sidecars/ — see sidecars/README.md");
            return;
        }

        let fixture = root.join("packs/app.kttl.subscription-audit/fixtures/statement-04.pdf");
        let lines = extract_lines(&fixture, &sidecars).unwrap();

        assert_eq!(
            lines
                .iter()
                .filter(|line| **line == "Date Description Paid Out Paid In Balance")
                .count(),
            6,
            "the header repeats on every page: {lines:#?}"
        );
        assert_eq!(
            lines
                .iter()
                .filter(|line| line.starts_with("Page ") && line.ends_with(" of 6"))
                .count(),
            6,
            "every page keeps its furniture: {lines:#?}"
        );
        let transaction_lines: Vec<&String> = lines
            .iter()
            .filter(|line| {
                line.as_bytes()
                    .first()
                    .is_some_and(|first| first.is_ascii_digit())
            })
            .collect();
        assert_eq!(transaction_lines.len(), 30, "{transaction_lines:#?}");

        // The finding this fixture exists to make undeniable.
        //
        // PUREGYM is money out (Paid Out 24.99). ACME PAYROLL is money in
        // (Paid In 2450.00). The CSV oracle says so —
        // `statement_04_csv_is_a_usable_oracle_for_its_pdf` in parse.rs.
        // After the space-join their lines have identical structure: date,
        // words, one amount, a balance. Nothing in the text tells them
        // apart.
        //
        // So #137 cannot be solved by parsing these strings. It has to keep
        // each fragment's horizontal position and decide which column an
        // amount sat in. Anyone who makes reconstruction pass by
        // pattern-matching lines will invert every credit in the statement,
        // and the report will look entirely confident about it.
        let numeric_shape = |line: &str| {
            line.split_whitespace()
                .map(|word| {
                    word.chars()
                        .all(|c| c.is_ascii_digit() || c == '.' || c == ',')
                })
                .collect::<Vec<bool>>()
        };
        let paid_out = lines
            .iter()
            .find(|line| line.contains("PUREGYM LTD"))
            .expect("a debit line");
        let paid_in = lines
            .iter()
            .find(|line| line.contains("ACME PAYROLL"))
            .expect("a credit line");
        assert_eq!(
            numeric_shape(paid_out),
            numeric_shape(paid_in),
            "the two directions must stay indistinguishable from the text alone — \
             if this ever differs, the fixture has stopped exercising the ambiguity"
        );
    }

    /// #137's acceptance test: the trusted CSV parser is the oracle.
    /// A plausible-looking PDF result is not enough; every date,
    /// merchant, magnitude and direction has to agree.
    #[test]
    fn statement_04_pdf_reconstructs_to_the_same_transactions_as_its_csv() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let sidecars = root.join("sidecars");
        if !runner::pdf::library_present(&sidecars) {
            eprintln!("skipping: no libpdfium in sidecars/ — see sidecars/README.md");
            return;
        }
        let fixtures = root.join("packs/app.kttl.subscription-audit/fixtures");

        let pages = extract_pages(&fixtures.join("statement-04.pdf"), &sidecars).unwrap();
        let from_pdf = reconstruct_statement(&pages).unwrap();
        let from_csv = parse_statement_file(&fixtures.join("statement-04.csv")).unwrap();

        assert!(from_pdf.warnings.is_empty(), "{:?}", from_pdf.warnings);
        assert_eq!(from_pdf.transactions, from_csv.transactions);
    }

    /// #218's acceptance test, on a real PDF rather than synthesised
    /// fragments: a signed Amount column plus a running Balance reads
    /// correctly, and reads correctly *in direction* — which is the
    /// only part that could fail silently.
    #[test]
    fn statement_05_reads_its_direction_out_of_the_running_balance() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let sidecars = root.join("sidecars");
        if !runner::pdf::library_present(&sidecars) {
            eprintln!("skipping: no libpdfium in sidecars/ — see sidecars/README.md");
            return;
        }
        let fixtures = root.join("packs/app.kttl.subscription-audit/fixtures");

        let pages = extract_pages(&fixtures.join("statement-05.pdf"), &sidecars).unwrap();
        let parsed = reconstruct_statement(&pages).expect("the balance settles the convention");

        assert!(parsed.warnings.is_empty(), "{:?}", parsed.warnings);
        assert_eq!(parsed.transactions.len(), 7);

        // One credit, six debits. Read the other way round this would
        // be six credits and one debit — a report claiming somebody
        // earned £190 and spent £2,450 that month, which is exactly as
        // plausible-looking as the truth.
        let credits: Vec<&str> = parsed
            .transactions
            .iter()
            .filter(|t| t.direction == Direction::Credit)
            .map(|t| t.raw_merchant.as_str())
            .collect();
        assert_eq!(credits, vec!["ACME PAYROLL"]);

        let payroll = parsed
            .transactions
            .iter()
            .find(|t| t.raw_merchant == "ACME PAYROLL")
            .expect("the payroll credit");
        assert_eq!(payroll.amount, Decimal::from_str("2450.00").unwrap());

        let gym = parsed
            .transactions
            .iter()
            .find(|t| t.raw_merchant == "PUREGYM LTD")
            .expect("the gym debit");
        assert_eq!(gym.amount, Decimal::from_str("24.99").unwrap());
        assert_eq!(gym.direction, Direction::Debit);
        assert_eq!(
            gym.date,
            NaiveDate::from_ymd_opt(2025, 1, 3).expect("a real date")
        );
    }

    /// The two signed-Amount fixtures differ in exactly one thing, and
    /// this pins it: statement-03 has no balance, so its direction is
    /// unknowable and it is refused; statement-05 has one, so it reads.
    /// If statement-03 ever starts parsing, the fail-closed rule has
    /// been lost.
    #[test]
    fn the_same_layout_without_a_balance_is_still_refused() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let sidecars = root.join("sidecars");
        if !runner::pdf::library_present(&sidecars) {
            eprintln!("skipping: no libpdfium in sidecars/ — see sidecars/README.md");
            return;
        }
        let fixtures = root.join("packs/app.kttl.subscription-audit/fixtures");

        let pages = extract_pages(&fixtures.join("statement-03.pdf"), &sidecars).unwrap();
        assert!(
            reconstruct_statement(&pages).is_err(),
            "statement-03 has one signed Amount column and nothing to check it against"
        );
    }

    /// #140: reading two statements in one session is ordinary — it is
    /// what someone with a current account and a card does, which is the
    /// case that motivated #136.
    ///
    /// libpdfium is a process-global singleton: `bind_to_library`
    /// refuses a second bind and `Pdfium::new` asserts on it. Binding
    /// per call meant the second read failed, and the failure claimed
    /// the PDF reader was missing when it had worked seconds earlier.
    #[test]
    fn two_statements_can_be_read_in_one_process() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let sidecars = root.join("sidecars");
        if !runner::pdf::library_present(&sidecars) {
            eprintln!("skipping: no libpdfium in sidecars/ — see sidecars/README.md");
            return;
        }
        let fixtures = root.join("packs/app.kttl.subscription-audit/fixtures");

        let first = extract_lines(&fixtures.join("statement-03.pdf"), &sidecars)
            .expect("the first statement reads");
        let second = extract_lines(&fixtures.join("statement-04.pdf"), &sidecars)
            .expect("and so does the second, in the same process");

        assert!(!first.is_empty());
        assert!(!second.is_empty());
        assert_ne!(first, second, "two different statements, two answers");

        // And a third, from the same path as the first: nothing about
        // reuse depends on the document being new.
        let again = extract_lines(&fixtures.join("statement-03.pdf"), &sidecars)
            .expect("re-reading a statement is not a new kind of thing");
        assert_eq!(again, first);
    }

    /// The other half of the same singleton problem: two threads
    /// binding at once corrupted memory outright (SIGSEGV), which is
    /// worse than an error because nothing survives to report it.
    #[test]
    fn two_threads_reading_at_once_do_not_corrupt_anything() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let sidecars = root.join("sidecars");
        if !runner::pdf::library_present(&sidecars) {
            eprintln!("skipping: no libpdfium in sidecars/ — see sidecars/README.md");
            return;
        }
        let fixture = root.join("packs/app.kttl.subscription-audit/fixtures/statement-04.pdf");

        let readers: Vec<_> = (0..4)
            .map(|_| {
                let (fixture, sidecars) = (fixture.clone(), sidecars.clone());
                std::thread::spawn(move || extract_lines(&fixture, &sidecars))
            })
            .collect();

        let answers: Vec<_> = readers
            .into_iter()
            .map(|reader| reader.join().expect("no thread died").expect("each reads"))
            .collect();
        assert!(answers.windows(2).all(|pair| pair[0] == pair[1]));
    }
}

fn frag(text: &str, x: f32, y: f32) -> Fragment {
    Fragment {
        text: text.to_owned(),
        x,
        right: x,
        y,
    }
}

fn cell(text: &str, left: f32, right: f32, y: f32) -> Fragment {
    Fragment {
        text: text.to_owned(),
        x: left,
        right,
        y,
    }
}

#[test]
fn positioned_paid_out_and_paid_in_reconstruct_to_opposite_directions() {
    let page = Page {
        fragments: vec![
            cell("Date", 40.0, 58.0, 750.0),
            cell("Description", 120.0, 170.0, 750.0),
            cell("Paid Out", 300.0, 340.0, 750.0),
            cell("Paid In", 385.0, 420.0, 750.0),
            cell("Balance", 485.0, 520.0, 750.0),
            cell("03 Jan 25", 40.0, 82.0, 728.0),
            cell("PUREGYM LTD", 120.0, 184.0, 728.0),
            cell("24.99", 316.0, 340.0, 728.0),
            cell("975.01", 490.0, 520.0, 728.0),
            cell("12 Jan 25", 40.0, 82.0, 706.0),
            cell("REFUND THETRAINLINE", 120.0, 220.0, 706.0),
            cell("18.50", 396.0, 420.0, 706.0),
            cell("993.51", 490.0, 520.0, 706.0),
            cell("Page 1 of 1", 40.0, 94.0, 60.0),
        ],
    };

    let parsed = reconstruct_statement(&[page]).expect("the positioned table reconstructs");

    assert!(parsed.warnings.is_empty(), "{:?}", parsed.warnings);
    assert_eq!(parsed.transactions.len(), 2);
    assert_eq!(
        parsed.transactions[0].date,
        NaiveDate::from_ymd_opt(2025, 1, 3).unwrap()
    );
    assert_eq!(parsed.transactions[0].raw_merchant, "PUREGYM LTD");
    assert_eq!(
        parsed.transactions[0].amount,
        Decimal::from_str("24.99").unwrap()
    );
    assert_eq!(parsed.transactions[0].direction, Direction::Debit);
    assert_eq!(
        parsed.transactions[1].date,
        NaiveDate::from_ymd_opt(2025, 1, 12).unwrap()
    );
    assert_eq!(parsed.transactions[1].direction, Direction::Credit);
}

#[test]
fn ambiguous_and_unreadable_pdf_amounts_are_warned_not_guessed() {
    let page = Page {
        fragments: vec![
            cell("Date", 40.0, 58.0, 750.0),
            cell("Description", 120.0, 170.0, 750.0),
            cell("Paid Out", 300.0, 340.0, 750.0),
            cell("Paid In", 385.0, 420.0, 750.0),
            cell("Balance", 485.0, 520.0, 750.0),
            cell("03 Jan 25", 40.0, 82.0, 728.0),
            cell("BROKEN VALUE", 120.0, 190.0, 728.0),
            cell("not money", 305.0, 340.0, 728.0),
            cell("975.01", 490.0, 520.0, 728.0),
            cell("04 Jan 25", 40.0, 82.0, 706.0),
            cell("BOTH COLUMNS", 120.0, 190.0, 706.0),
            cell("10.00", 316.0, 340.0, 706.0),
            cell("10.00", 396.0, 420.0, 706.0),
            cell("975.01", 490.0, 520.0, 706.0),
        ],
    };

    let parsed = reconstruct_statement(&[page]).expect("the layout itself is known");

    assert!(parsed.transactions.is_empty());
    assert_eq!(parsed.warnings.len(), 2, "{:?}", parsed.warnings);
    assert!(parsed.warnings[0].contains("could not read an amount"));
    assert!(parsed.warnings[1].contains("ambiguous"));
}

#[test]
fn whitespace_fragments_are_dropped() {
    // pdfium segments arrive with trailing spaces of their own — one
    // space between fragments, however much padding they carry.
    let fragments = [
        frag("  ", 10.0, 700.0),
        frag("BRITISH GAS ", 60.0, 700.0),
        frag("", 300.0, 700.0),
        frag(" 42.50", 400.0, 700.0),
    ];

    assert_eq!(
        lines_from_fragments(&fragments),
        vec!["BRITISH GAS 42.50".to_owned()]
    );
}

#[test]
fn pdf_failures_offer_only_an_alternative_the_bank_might_have() {
    let failures = [
        PdfError::LibraryMissing,
        PdfError::ReaderUnavailable("not available".to_owned()),
        PdfError::NoText,
        PdfError::UnrecognisedLayout,
        PdfError::UndeterminedDirection,
    ];

    for failure in failures {
        let message = failure.to_string();
        assert!(
            message.contains("if your bank offers one"),
            "{message:?} should not prescribe an unavailable export"
        );
        assert!(
            !message.contains("export a CSV"),
            "{message:?} promises an option many banks do not provide"
        );
    }
}

#[test]
fn an_unsigned_amount_header_does_not_establish_what_the_sign_means() {
    // Refused, as it always was. What changed with #218 is *which*
    // refusal: the columns here are perfectly legible, so blaming them
    // sent people looking for a layout problem that was not there. The
    // real answer is that this table cannot say which way its money
    // goes, and now the error says so.
    let page = Page {
        fragments: vec![
            cell("Date", 40.0, 90.0, 720.0),
            cell("Description", 120.0, 240.0, 720.0),
            cell("Amount", 380.0, 430.0, 720.0),
            cell("03/01/2025", 40.0, 90.0, 700.0),
            cell("PUREGYM LTD", 120.0, 240.0, 700.0),
            cell("-24.99", 390.0, 430.0, 700.0),
        ],
    };

    assert!(matches!(
        reconstruct_statement(&[page]),
        Err(PdfError::UndeterminedDirection)
    ));
}

#[test]
fn fragments_rebuild_reading_order_lines() {
    // PDF user space: y increases up the page. Fragments arrive in the
    // order the PDF happens to store them, with slight y jitter within
    // a visual row.
    let fragments = [
        frag("24.99", 400.0, 700.0),
        frag("03/01/2025", 60.0, 700.5),
        frag("PUREGYM LTD", 180.0, 700.0),
        frag("Date", 60.0, 720.0),
        frag("Description", 180.0, 719.6),
        frag("Amount", 400.0, 720.2),
    ];

    assert_eq!(
        lines_from_fragments(&fragments),
        vec![
            "Date Description Amount".to_owned(),
            "03/01/2025 PUREGYM LTD 24.99".to_owned(),
        ]
    );
}

// ---------------------------------------------------------------------------
// #218: Date / Description / Amount / Balance, where one signed money
// column carries the direction.
//
// The rule these tests exist to hold: the sign convention is *read from
// the document*, never assumed. A signed Amount column alone cannot say
// whether -24.99 means money out or money in — both conventions are real
// and both appear in real exports. A running Balance can say, because
// the arithmetic only reconciles one way. So the layout is supported
// exactly when the balance proves it, and refused when it does not.
//
// Guessing here is how you silently invert someone's spending, which is
// worse than refusing to read the file.

/// Date / Description / Amount / Balance at fixed columns, one row per
/// transaction, top row the header.
fn amount_and_balance(rows: &[(&str, &str, &str, &str)]) -> Page {
    // Real extents, not points: the money columns are right-aligned and
    // matched on their right edge, exactly as the Paid Out / Paid In
    // layout is.
    let mut fragments = vec![
        cell("Date", 40.0, 90.0, 720.0),
        cell("Description", 120.0, 240.0, 720.0),
        cell("Amount", 380.0, 430.0, 720.0),
        cell("Balance", 480.0, 540.0, 720.0),
    ];
    for (index, (date, merchant, amount, balance)) in rows.iter().enumerate() {
        let y = 700.0 - 20.0 * index as f32;
        fragments.push(cell(date, 40.0, 90.0, y));
        fragments.push(cell(merchant, 120.0, 240.0, y));
        fragments.push(cell(amount, 390.0, 430.0, y));
        fragments.push(cell(balance, 490.0, 540.0, y));
    }
    Page { fragments }
}

#[test]
fn a_running_balance_says_that_a_negative_amount_is_money_out() {
    // Each balance is the one before it *plus* the signed amount, so
    // the only convention that reconciles is "negative means out".
    let page = amount_and_balance(&[
        ("03/01/2025", "PUREGYM LTD", "-24.99", "975.01"),
        ("15/01/2025", "NETFLIX.COM", "-10.99", "964.02"),
        ("28/01/2025", "ACME PAYROLL", "2450.00", "3414.02"),
    ]);

    let parsed = reconstruct_statement(&[page]).expect("the balance establishes the convention");
    let directions: Vec<_> = parsed
        .transactions
        .iter()
        .map(|t| (t.raw_merchant.as_str(), t.amount.to_string(), t.direction))
        .collect();

    assert_eq!(
        directions,
        vec![
            ("PUREGYM LTD", "24.99".to_owned(), Direction::Debit),
            ("NETFLIX.COM", "10.99".to_owned(), Direction::Debit),
            ("ACME PAYROLL", "2450.00".to_owned(), Direction::Credit),
        ]
    );
}

#[test]
fn a_running_balance_says_the_opposite_when_the_document_does() {
    // The same three transactions, same real-world meaning, written the
    // other way round: a positive amount is money out, and the balance
    // falls by it. Nothing about the amounts alone distinguishes this
    // file from the one above — only the arithmetic does.
    let page = amount_and_balance(&[
        ("03/01/2025", "PUREGYM LTD", "24.99", "975.01"),
        ("15/01/2025", "NETFLIX.COM", "10.99", "964.02"),
        ("28/01/2025", "ACME PAYROLL", "-2450.00", "3414.02"),
    ]);

    let parsed = reconstruct_statement(&[page]).expect("the balance establishes the convention");
    let directions: Vec<_> = parsed
        .transactions
        .iter()
        .map(|t| (t.raw_merchant.as_str(), t.amount.to_string(), t.direction))
        .collect();

    // Identical to the previous test. That is the whole point: the
    // file's convention changed, the meaning did not.
    assert_eq!(
        directions,
        vec![
            ("PUREGYM LTD", "24.99".to_owned(), Direction::Debit),
            ("NETFLIX.COM", "10.99".to_owned(), Direction::Debit),
            ("ACME PAYROLL", "2450.00".to_owned(), Direction::Credit),
        ]
    );
}

#[test]
fn one_transaction_cannot_establish_a_convention_on_its_own() {
    // A single row has no preceding balance to be a delta from, so
    // nothing here reconciles either way. Refused, not guessed.
    let page = amount_and_balance(&[("03/01/2025", "PUREGYM LTD", "-24.99", "975.01")]);

    assert!(matches!(
        reconstruct_statement(&[page]),
        Err(PdfError::UndeterminedDirection)
    ));
}

#[test]
fn a_balance_that_reconciles_both_ways_establishes_nothing() {
    // Every amount is zero, so `balance + amount` and `balance - amount`
    // agree on every row. Two conventions that both fit is the same
    // amount of evidence as none.
    let page = amount_and_balance(&[
        ("03/01/2025", "ADJUSTMENT", "0.00", "975.01"),
        ("15/01/2025", "ADJUSTMENT", "0.00", "975.01"),
        ("28/01/2025", "ADJUSTMENT", "0.00", "975.01"),
    ]);

    assert!(matches!(
        reconstruct_statement(&[page]),
        Err(PdfError::UndeterminedDirection)
    ));
}

#[test]
fn a_document_that_switches_convention_halfway_is_refused() {
    // Row 2 reconciles as balance + amount; row 3 only as balance -
    // amount. One of them is wrong and nothing here says which, so the
    // file is refused rather than half-read.
    let page = amount_and_balance(&[
        ("03/01/2025", "PUREGYM LTD", "-24.99", "975.01"),
        ("15/01/2025", "NETFLIX.COM", "-10.99", "964.02"),
        ("28/01/2025", "TESCO STORES", "40.00", "924.02"),
    ]);

    assert!(matches!(
        reconstruct_statement(&[page]),
        Err(PdfError::UndeterminedDirection)
    ));
}

#[test]
fn a_refusal_to_establish_direction_says_so_rather_than_blaming_the_columns() {
    // The columns were recognised perfectly well. Saying "could not
    // recognise the transaction columns" would send someone looking for
    // a layout problem that isn't there.
    let message = PdfError::UndeterminedDirection.to_string();

    assert!(
        !message.contains("recognise the transaction columns"),
        "{message:?} blames the wrong thing"
    );
    assert!(
        message.contains("if your bank offers one"),
        "{message:?} should not prescribe an export the bank may not have"
    );
}
